In [1]:
# Install python package - Numpy

In [2]:
# Install python package - Numpy
#pip install numpy

In [42]:
import numpy as np

In [4]:
mylist=[1,2,3,4,5]
stringlist=["apple","orange"]

In [5]:
print(mylist)

[1, 2, 3, 4, 5]


In [6]:
type(mylist)

list

In [7]:
#dir(np)

In [8]:
#help(np)

In [9]:
 arr=np.array(mylist)

In [10]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
#shape of the array
arr.shape

(5,)

In [12]:
arr.size

5

In [13]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,4,5,7,7]
my_lst3=[3,4,3,8,8]
arr1=np.array([my_lst1,my_lst2,my_lst3])

In [14]:
type(arr1)

numpy.ndarray

In [15]:
arr1.shape

(3, 5)

In [16]:
arr1.size

15

In [17]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 7, 7],
       [3, 4, 3, 8, 8]])

In [18]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 7, 7],
       [3, 4, 3, 8, 8]])

In [19]:
print(arr1)

[[1 2 3 4 5]
 [2 4 5 7 7]
 [3 4 3 8 8]]


In [20]:
#numpy array indexing


my_lst1=[1,2,3,4,5]
arr2=np.array(my_lst1)

In [21]:
#print the first elemnet in array
print(arr2[0])

1


In [22]:
#print the second elemnet in array
print(arr2[1])

2


In [23]:
print("the third element is" ,arr2[3])

the third element is 4


In [24]:
#negative indexing
mylist=[1,2,3,4,5,6]
arr3= np.array(mylist)
#print(arr3)
valarr=np.array([[1,2,3],[4,5,6]])
print(valarr)


[[1 2 3]
 [4 5 6]]


In [25]:
valarr[1,-2]

5

In [26]:
#numpy array slicing
mylist=[1,2,3,4,5,6,7]
arr4= np.array(mylist)
print(arr)


[1 2 3 4 5]


In [27]:
arr4

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
arr4[0:5]

array([1, 2, 3, 4, 5])

In [29]:
arr4[3:]

array([4, 5, 6, 7])

In [30]:
arr4[0:5]

array([1, 2, 3, 4, 5])

In [31]:
#slicing 2d arrays
arr[:2,1:4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
#arange function

np.arange(10)

In [ ]:
np.arange(27,37)

In [ ]:
np.arange(10,20,2)

In [ ]:
#linspace
np.linspace(0,100)

In [ ]:
arr=np.array([10, 12, 14, 16, 18])
print(arr.dtype)

In [ ]:
#datatype

arr=np.array([10, 12, 14, 16, 18],dtype="S")
print(arr.dtype)

In [ ]:
arr=np.array([10, 12, 14, 16, 18],dtype=np.float32)
print(arr.dtype)

In [45]:
#numpy array copy as view
arr1= np.array([1,2,3,4,5,6])
x=arr1

In [46]:
arr1[0]=100

In [47]:
print(arr1)

[100   2   3   4   5   6]


In [49]:
print(x)

[100   2   3   4   5   6]


In [50]:
x[1]=200

In [51]:
print(x)

[100 200   3   4   5   6]


In [52]:
print(arr1)

[100 200   3   4   5   6]


In [53]:
#numpy array as copy
arr1= np.array([1,2,3,4,5,6])
x= arr1.copy()

In [54]:
print(arr1)

[1 2 3 4 5 6]


In [64]:
#numpy array reshaping
#1D........>2D
arr=np.arange(1,13)
arr.shape
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [68]:
arr_new=arr.reshape(3,4)

In [67]:
#flattering the arrays
#2D.........>1D
arr_new.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
#Iterating Arrays
arr=np.arange(1,7).reshape(3,2)


In [76]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
for x in arr:
    print(x)

[1 2]
[3 4]
[5 6]


In [78]:
#joining numpy Arrays
arr1=np.arange(1,4)
arr2=np.arange(4,7)

In [79]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])